---
theme_spec: scripts/thesis_theme.R

fonts_path: fonts/

tss_fdr_cutoff: 0.1

figures:
    six:
        gene_diagram:
            width: 2.75
            height: 1
        aat_assay_comparison:
            width: 6
            height: 4
            data_path: ../../intragenic/spt6-data-integration/browser-shots/AAT2/AAT2_all-assays.tsv.gz
    stress:
        tfiib_ridgelines:
            width: 6
            height: 8.25
            data_path: /n/groups/winston/jc459/intragenic/chipnexus-tfiib/datavis/genes-with-stress-induced-intra-peaks/libsizenorm/genes-with-stress-induced-intra-peaks-allsamples-allannotations-tfiib-chipnexus-libsizenorm-protection.tsv.gz
            diamide_genic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/diamide-v-YPD/libsizenorm/genic/diamide-v-YPD_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-genic-all.tsv
            diamide_intragenic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/diamide-v-YPD/libsizenorm/intragenic/diamide-v-YPD_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-intragenic-all.tsv
            amino_genic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/SD-v-SC/libsizenorm/genic/SD-v-SC_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-genic-all.tsv
            amino_intragenic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/SD-v-SC/libsizenorm/intragenic/SD-v-SC_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-intragenic-all.tsv
            nitrogen_genic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/nitrogen-v-SC/libsizenorm/genic/nitrogen-v-SC_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-genic-all.tsv
            nitrogen_intragenic: /n/groups/winston/jc459/intragenic/chipnexus-tfiib-custom-analysis/diff_binding/peaks/nitrogen-v-SC/libsizenorm/intragenic/nitrogen-v-SC_tfiib-chipnexus-libsizenorm-peaks-diffbind-results-intragenic-all.tsv
            annotations:
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_1-DiaAminoNit.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_2-DiaAmino.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_3-DiaNit.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_4-AminoNit.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_5-Dia.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_6-Amino.bed
                - ../../intragenic/genome/annotations/orfs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort/ORFs_w_stress_induced_intragenic_TFIIB_peaks_ATGdistsort_group_7-Nit.bed
        tfiib_coverage:
            width: 6
            height: "9/16*6"
            transcript_annotation: ../../intragenic/genomefiles_cerevisiae/annotations/Scer_polIItranscripts-adjustedTSS.bed
            orf_annotation: ../../intragenic/genome/annotations/Scer_nondubious_ORFs_and_blocked_reading_frames-adjustedATG.bed
            data:
                ASE1:
                    paths:
                        - ../../intragenic/stress-data-integration/browser-shots/ASE1-diamide/ASE1-diamide_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/ASE1-aminoacid/ASE1-aminoacid_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/ASE1-nitrogen/ASE1-nitrogen_TFIIB-ChIP-nexus-protection.tsv.gz
                    upstream: 300
                    downstream: 0
                DSK2:
                    paths:
                        - ../../intragenic/stress-data-integration/browser-shots/DSK2-diamide/DSK2-diamide_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/DSK2-aminoacid/DSK2-aminoacid_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/DSK2-nitrogen/DSK2-nitrogen_TFIIB-ChIP-nexus-protection.tsv.gz
                    upstream: 350
                    downstream: 0
                HEM15:
                    paths:
                        - ../../intragenic/stress-data-integration/browser-shots/HEM15-diamide/HEM15-diamide_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/HEM15-aminoacid/HEM15-aminoacid_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/HEM15-nitrogen/HEM15-nitrogen_TFIIB-ChIP-nexus-protection.tsv.gz
                    upstream: 250
                    downstream: 0
                RRT8:
                    paths:
                        - ../../intragenic/stress-data-integration/browser-shots/RRT8-diamide/RRT8-diamide_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/RRT8-aminoacid/RRT8-aminoacid_TFIIB-ChIP-nexus-protection.tsv.gz
                        - ../../intragenic/stress-data-integration/browser-shots/RRT8-nitrogen/RRT8-nitrogen_TFIIB-ChIP-nexus-protection.tsv.gz
                    upstream: 350
                    downstream: 0
        promoter_tss_diffexp_summary:
            genic_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/genic/diamide-v-YPD_genic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            intra_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/intragenic/diamide-v-YPD_intragenic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            anti_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/antisense/diamide-v-YPD_antisense-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            inter_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/intergenic/diamide-v-YPD_intergenic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            height: 4
            width: 3
        promoter_tss_expression:
            genic_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/genic/diamide-v-YPD_genic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200-matched-up.tsv
            intra_path: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/intragenic/diamide-v-YPD_intragenic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200-matched-up.tsv
            counts_path: ../../intragenic/tss-seq/diff_exp/peaks/diamide-v-YPD/spikenorm/diamide-v-YPD_tss-seq-spikenorm-peaks-counts-rlogtransformed.tsv
            height: 4
            width: 6
        promoter_tss_polyenrichment:
            matched_peaks_genic: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/genic/diamide-v-YPD_genic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            matched_peaks_intra: ../../intragenic/tss-v-tfiib-nexus/matched_peaks/diamide-v-YPD/tfiib_matched_to_tss/intragenic/diamide-v-YPD_intragenic-tss-seq-spikenorm-tfiib-libsizenorm-matched-peaks-distance200.tsv
            polyenrichment_genic: ../../intragenic/polysome-diamide-tss-comparison/diff_exp/peaks/diamide-v-YPD/spikenorm/diamide-v-YPD_tss-seq-spikenorm-peaks-diffexp-results-with-polysome-enrichment-genic.tsv
            polyenrichment_intra: ../../intragenic/polysome-diamide-tss-comparison/diff_exp/peaks/diamide-v-YPD/spikenorm/diamide-v-YPD_tss-seq-spikenorm-peaks-diffexp-results-with-polysome-enrichment-intragenic.tsv
            height: 4
            width: 6
